name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main    # ili master, koju god granu koristiš za source

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - run: npm ci

      - run: npm run build      # zamijeni ako tvoj build task nosi drugo ime

      - uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./public
          github_token: ${{ secrets.GITHUB_TOKEN }}
